# Generated by Django 3.2 on 2021-07-12 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='attachment',
            field=models.CharField(default='x.jpg', max_length=255),
        ),
    ]
